// savemate/styles/SaveMateStyles.js
import { StyleSheet } from 'react-native';

const PILL_SIZE = 34;
const PILL_RADIUS = 12;

export const SaveMateStyles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#F9FAFB' },
  header: { backgroundColor: '#FFFFFF', paddingVertical: 16, alignItems: 'center' },
  appTitle: { fontSize: 22, fontWeight: '700', color: '#7C3AED' },
  content: { padding: 16, paddingBottom: 120, gap: 12 },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 15,
    padding: 20,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  cardTitle: { fontSize: 16, fontWeight: '600', color: '#7C3AED', marginBottom: 6 },
  cardText: { fontSize: 14, color: '#1F2937' },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline' },
  rowCenter: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  totalAmount: { fontSize: 26, fontWeight: '700', color: '#111827' },
  comparisonText: { fontSize: 12, color: '#6B7280', textAlign: 'right', marginBottom: 12 },
  chevron: { fontSize: 20, color: '#9CA3AF' },
  progressText: { fontSize: 20, fontWeight: '700', color: '#111827' },
  progressBarBg: {
    width: '100%',
    height: 10,
    backgroundColor: '#E5E7EB',
    borderRadius: 999,
    overflow: 'hidden',
    marginTop: 20
  },
  progressBarFill: { height: '100%', backgroundColor: '#8B5CF6', borderRadius: 999 },
  btnGhost: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    marginRight: 8,
  },
  btnGhostText: { color: '#374151', fontSize: 14 },
  btnPrimary: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 999,
    backgroundColor: '#F3E8FF',
    borderWidth: 1,
    borderColor: '#F3E8FF',
  },
  btnPrimaryText: { color: '#7C3AED', fontSize: 14, fontWeight: '600' },
  fab: {
    position: 'absolute',
    right: 16,
    bottom: 96,
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: '#FFFFFF',
    borderWidth: 2,
    borderColor: '#8B5CF6',
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 4,
  },
  fabPlus: { fontSize: 32, color: '#7C3AED', lineHeight: 34 },
  bottomNavWrapper: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 1,
    borderTopColor: '#E5E7EB',
  },
  bottomNav: {
    height: 80,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingHorizontal: 16,
  },
  navBtn: { alignItems: 'center' },
  navIcon: { fontSize: 20, color: '#9CA3AF' },
  navLabel: { fontSize: 12, color: '#9CA3AF', marginTop: 2, fontWeight: '500' },
  navActive: { color: '#7C3AED' },
  detailHeader: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 12,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems:'center',
    justifyContent: 'space-between',
  },
  backBtn: { padding: 4 },
  backChevron: { fontSize: 22, color: '#7C3AED' },
  detailTitle: { fontSize: 22, fontWeight: '700', color: '#7C3AED' },
  monthBtn: { paddingHorizontal: 8, paddingVertical: 4 },
  monthChevron: { fontSize: 18, color: '#3B82F6' },
  monthChevronDisabled: { color: '#D1D5DB' },
  weekHeaderRow: { flexDirection: 'row', marginBottom: 6, marginTop: 4 },
  weekHeaderText: {
    flex: 1,
    textAlign: 'center',
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '600',
    paddingVertical: 6,
  },
  calendarGrid: { flexDirection: 'row', flexWrap: 'wrap' },
  dayCell: {
    width: `${100 / 7}%`,
    aspectRatio: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pillText: {
    minWidth: PILL_SIZE,
    height: PILL_SIZE,
    paddingHorizontal: 8,
    borderRadius: PILL_RADIUS,
    fontSize: 16,
    fontWeight: '700',
    color: '#111827',
    textAlign: 'center',
    lineHeight: PILL_SIZE,
    textAlignVertical: 'center',
    includeFontPadding: false,
  },
  pillBlueBg: { backgroundColor: '#DBEAFE', color: '#2563EB' },
  pillPurpleBg: { backgroundColor: '#F3E8FF', color: '#7C3AED' },
  blueText: { color: '#3B82F6' },
  boldText: { fontWeight: '800' },
  dayTitle: { fontSize: 15, fontWeight: '600', color: '#111827', marginBottom: 12 },
  txnRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 10 },
  txnDivider: { borderBottomWidth: 1, borderBottomColor: '#F3F4F6' },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  txnBody: { flex: 1 },
  amountText: { fontSize: 18, fontWeight: '700' },
  income: { color: '#10B981' },
  expense: { color: '#EF4444' },
  txnMeta: { fontSize: 13, color: '#4B5563', marginTop: 2 },
  emptyText: { fontSize: 13, color: '#9CA3AF' },

  // ===== 만족도 평가 스타일 =====
  satisfactionQuestion: { fontSize: 15, color: '#1F2937', marginBottom: 16, textAlign: 'center' },
  amountBox: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
  },
  satisfactionAmount: { fontSize: 26, fontWeight: '700', color: '#111827', marginBottom: 4 },
  satisfactionDate: { fontSize: 13, color: '#6B7280' },
  emojiRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 12 },
  emojiButton: {
    flex: 1,
    backgroundColor: '#E5E7EB',
    borderRadius: 12,
    padding: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emojiButtonSelected: { borderWidth: 2 },
  emojiButtonDissatisfied: { backgroundColor: '#FEE2E2', borderColor: '#EF4444' },
  emojiButtonNeutral: { backgroundColor: '#FEF3C7', borderColor: '#F59E0B' },
  emojiButtonSatisfied: { backgroundColor: '#D1FAE5', borderColor: '#10B981' },
  emojiIcon: { fontSize: 40, marginBottom: 8 },
  emojiLabel: { fontSize: 14, fontWeight: '600', color: '#374151' },
  sectionTitle: { fontSize: 15, fontWeight: '600', color: '#111827', marginBottom: 12 },
  reasonGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  reasonChip: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 999,
    backgroundColor: '#F3F4F6',
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  reasonChipSelected: {
    backgroundColor: '#F3E8FF',
    borderColor: '#7C3AED',
  },
  reasonChipText: { fontSize: 14, color: '#4B5563' },
  reasonChipTextSelected: { color: '#7C3AED', fontWeight: '600' },
  memoInput: {
    backgroundColor: '#F9FAFB',
    borderRadius: 8,
    padding: 12,
    fontSize: 14,
    color: '#111827',
    minHeight: 100,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  buttonRow: { flexDirection: 'row', gap: 12, marginTop: 8 },
  btnSecondary: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    alignItems: 'center',
  },
  btnSecondaryText: { fontSize: 15, color: '#374151', fontWeight: '600' },
  btnPrimaryLarge: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    backgroundColor: '#F3E8FF',
    borderWidth: 1,
    borderColor: '#F3E8FF',
    alignItems: 'center',
  },
  btnPrimaryLargeText: { fontSize: 15, color: '#7C3AED', fontWeight: '600' },
});
